======================
-- Exercise Answers --
======================
--Question 1
CREATE OR REPLACE VIEW EMP_VU AS 
SELECT EMPLOYEEID, LNAME, FNAME, POSITIONID, SUPERVISOR, HIREDATE, DEPTID, QUALID FROM EMPLOYEE;

--Question 2
CREATE OR REPLACE VIEW DEPT_SAL_VU AS
SELECT deptname, AVG(salary) AVGSALARY FROM employee e, dept d WHERE e.deptid=d.deptid GROUP BY deptname;

--Question 3
SELECT * FROM EMPLOYEE WHERE EMPLOYEEID = 123 FOR UPDATE OF SALARY NOWAIT;
UPDATE EMPLOYEE SET SALARY=100000 WHERE EMPLOYEEID=123;
SELECT * FROM EMPLOYEE WHERE EMPLOYEEID = 123;
ROLLBACK;
SELECT * FROM EMPLOYEE WHERE EMPLOYEEID = 123;
COMMIT;

--Question 4
CREATE OR REPLACE VIEW EMP_TOTSAL_VU AS
SELECT EMPLOYEEID, LNAME, FNAME, SALARY+NVL(COMMISSION,0) TOTSAL, DEPTID FROM EMPLOYEE
WHERE DEPTID=10 WITH CHECK OPTION;

--Insert fails because of "with check option where clause" violation
INSERT INTO EMP_TOTSAL_VU (EMPLOYEEID, FNAME, LNAME, DEPTID)
VALUES(600, 'James', 'Wheeler', 20);

--No violation occurs
INSERT INTO EMP_TOTSAL_VU (EMPLOYEEID, FNAME, LNAME, DEPTID)
VALUES(600, 'James', 'Wheeler', 10);

--Update employee's data
UPDATE EMPLOYEE SET POSITIONID=4, SUPERVISOR=123, HIREDATE=TO_DATE('01-01-2019', 'DD-MM-YYYY'), SALARY=30000, QUALID=3 WHERE EMPLOYEEID=600;

--Question 5
CREATE OR REPLACE VIEW EMPLOYEE_DEPT_SAL_VU AS
SELECT DEPTNAME, SUM(SALARY+NVL(COMMISSION,0)) TOTALSALARY
FROM EMPLOYEE E, DEPT D WHERE E.DEPTID = D.DEPTID GROUP BY DEPTNAME;

--Question 6
CREATE SEQUENCE DEPTID_SEQ START WITH 50 INCREMENT BY 10 MAXVALUE 90 NOCACHE;

CREATE SEQUENCE EMPID_SEQ START WITH 601 MAXVALUE 999 NOCACHE;

INSERT INTO DEPT VALUES (DEPTID_SEQ.NEXTVAL, 'Projects', 'Istanbul', 111);

INSERT INTO EMPLOYEE(EMPLOYEEID, FNAME, LNAME, SALARY, DEPTID) 
VALUES (EMPID_SEQ.NEXTVAL, 'David', 'Stone', 90000, DEPTID_SEQ.CURRVAL);

SELECT * FROM DEPT;
SELECT * FROM EMPLOYEE;
